
---
version: "2"

services:
  php-apache:
    image: grav-php-apache:latest
    container_name: grav-php-apache
    ports:
      - "80:80"
    restart: always
    # See 'Custom PHP codebase' for instructions for volumes.
    volumes:
      - ./web:/var/www/html:rw
